project:
  type: website
  output-dir: docs

website:
  title: "The Trumpet"
  navbar:
    logo: archive/figures/trumpet_white.png
    right:
      - weather-station.qmd
      - text: "Israel"
        href: israel.qmd
      - text: "UGA"
        href: uga.qmd
      - media.qmd


format:
  html:
    include-before-body: _custom_header.html
    theme:
      - flatly
      - custom.scss
    css: styles.css
    highlight-style: breezedark
    fontsize: 1.25em



