project:
  type: website
  output-dir: docs

website:
  title: "uten box"
  navbar:
    right:
      - the_box.qmd
      - weather-station.qmd
      - text: "Israel"
        href: israel-mango.qmd
      - text: "UGA"
        href: uga.qmd


format:
  html:
    include-before-body: _custom_header.html
    theme:
      - flatly
      - custom.scss
    css: styles.css
    highlight-style: breezedark



